todo/core/urls.py
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name = 'core'
urlpatterns = [
    path('', views.todo_list, name='todo_list'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout_user, name='logout'),
    path('about/', views.about, name='about'),
    path('todo/add', views.new_todo_form, name='new_todo_form'),
    path('todo/edit/<int:todo_id>', views.edit_todo_form, name='edit_todo_form'),
    path('todo/delete/<int:todo_id>', views.delete_todo, name='delete_todo'),
    path('todo/status/<int:todo_id>', views.change_todo_status, name='change_todo_status'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

todo/core/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.
class Todo(models.Model):
    """
    Django model.
    Details one specific Todo item belonging to a User.
    """

    class TodoStatus(models.TextChoices):
        """
        Enumerates the 2 possible states of a Todo.
        """
        PENDING = 'P', _('Pending')
        COMPLETED = 'C', _('Completed')

    title = models.CharField(max_length=255, blank=False, null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    notes = models.TextField(blank=True, default='')
    status = models.CharField(max_length=1, choices=TodoStatus, default=TodoStatus.PENDING, blank=False, null=False)

todo/core/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms
from .models import Todo


class SignupForm(UserCreationForm):
    """
    Django UserCreationForm.
    Sets up user creation form and adds CSS bootstrap classes and HTML placeholders.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # loop through fields and adds a bootstrap form-control class
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"

        self.fields['username'].widget.attrs.update({'placeholder': 'type your username'})
        self.fields['email'].widget.attrs.update({'placeholder': 'type your email'})
        self.fields['first_name'].widget.attrs.update({'placeholder': 'type your first name'}, required=True)
        self.fields['last_name'].widget.attrs.update({'placeholder': 'type your last name'}, required=True)
        self.fields['password1'].widget.attrs.update({'placeholder': 'type your password'})
        self.fields['password2'].widget.attrs.update({'placeholder': 'confirm your password'})

    class Meta:
        """
        Django Meta inner class.
        """
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']


class LoginForm(AuthenticationForm):
    """
    Django AuthenticationForm.
    Sets up authentication form and adds CSS bootstrap classes and HTML placeholders.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # loop through fields and adds a bootstrap form-control class
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"

        self.fields['username'].widget.attrs.update({'placeholder': 'type your username'})
        self.fields['password'].widget.attrs.update({'placeholder': 'type your password'})

    class Meta:
        model = User
        fields = ['username', 'password']


class TodoForm(forms.ModelForm):
    """
    Django ModelForm.
    Allows creation and modification of a Todo.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # loop through fields and adds a bootstrap form-control class
        for field in self.fields.values():
            field.widget.attrs["class"] = "form-control"

        self.fields['title'].widget.attrs.update({'placeholder': 'My New Todo'}, required=True)
        self.fields['notes'].widget.attrs.update({'placeholder': 'My New Todo Notes (optional)'})

    class Meta:
        """
        Django Meta inner class.
        """
        model=Todo
        fields=['title', 'notes']

todo/core/views.py
import json
from datastar_py.sse import ServerSentEventGenerator
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied, ObjectDoesNotExist
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .forms import SignupForm, LoginForm, TodoForm
from django.contrib import auth
from .models import Todo


def login(request):
    """
    Django view.
    Display login page to user.

    :param request: Django request
    :return: rendered login template if request is GET (or if there are errors), else returns redirect to to_do list view
    """
    if request.method == 'GET':
        form = LoginForm()
        return render(request, 'login.html', {'form': form})

    if request.method == 'POST':
        form = LoginForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = auth.authenticate(username=username, password=password)
            if user is not None:
                auth.login(request, user)
                return redirect('core:todo_list')
        else:
            # errors logging in
            return render(request, 'login.html', {'form': form})


def signup(request):
    """
    Django view.
    Display signup page.

    :param request: Django request
    :return: rendered signup template if request is GET (or there are errors), else return redirect to dashboard view
    """
    if request.method == 'GET':
        form = SignupForm()
        return render(request, 'signup.html', {'form': form})

    if request.method == 'POST':
        form = SignupForm(data=request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = auth.authenticate(username=username, password=password)
            if user is not None:
                auth.login(request, user)
                return redirect('core:todo_list')
        else:
            # user is not created
            return render(request, 'signup.html', {'form': form})


@login_required
def logout_user(request):
    """
    Django view.
    Log out the current user.

    :param request: Django request
    :return: redirect to login page
    """
    auth.logout(request)
    return redirect('core:login')


def about(request):
    return render(request, 'about.html')


@login_required
def todo_list(request):
    """
    Django view.
    Display the Todo List.

    :param request: Django request
    :return: rendered todo_list template
    """
    todos = Todo.objects.filter(user=request.user).order_by('title')

    page = 1
    keyword_input = ""
    status_input = ""
    try:
        qdict = json.loads(request.GET.get("datastar", "{}"))
        page = int(qdict.get("page", 1)) if qdict.get("page") else 1
        keyword_input = qdict.get("keyword", "")
        status_input = qdict.get("status", "")
    except TypeError:
        pass

    # if there is todo status input, filter by pending or completed todos
    if status_input:
        if status_input == 'pending':
            todos = todos.filter(status='P')
        elif status_input == 'completed':
            todos = todos.filter(status='C')

    # if there is keyword input, search for keyword in title and notes
    if keyword_input:
        todos = todos.filter(notes__icontains=keyword_input).union(todos.filter(title__icontains=keyword_input))

    # pagination
    paginator = Paginator(todos, 10)
    todo_paginator = paginator.get_page(page)
    context = {'todos': todo_paginator}

    # return datastar requests as server sent events
    if "datastar" in request.GET:
        # render only list template partial
        html_response = render(
            request, "todo_list.html#todo_list_card", context=context
        )

        # merge rendered template partial with the rest of the template
        sse_response = ServerSentEventGenerator.merge_fragments(
            html_response.content.decode("utf-8").splitlines()
        )
        response = HttpResponse(sse_response)
        response["Content-Type"] = "text/event-stream"
        response["Cache-Control"] = "no-cache"
        return response

    # not a datastar request, return regular render
    return render(request, 'todo_list.html', context=context)


@login_required
def change_todo_status(request, todo_id):
    """
    Django view.
    Swap the status of the given Todo object.

    :param request: Django request
    :param todo_id: id of the Todo to update
    :return: redirect to list view
    """

    # error handling
    try:
        todo = Todo.objects.get(id=todo_id)

        # if the todo doesn't belong to that user, raise exception
        if todo.user != request.user:
            raise PermissionDenied
    except (PermissionDenied, ObjectDoesNotExist):
        return redirect('core:todo_list')

    # flip status
    todo.status = 'C' if todo.status == 'P' else 'P'
    todo.save()
    return redirect('core:todo_list')


@login_required
def new_todo_form(request):
    """
    Django view.
    Display new Todo form and handle creation of new Todo.

    :param request: Django request
    :return: redirect to list view
    """
    if request.method == 'GET':
        context = {'form': TodoForm(), 'form_type': 'add'}
        return render(request, 'todo_form.html', context)
    if request.method == 'POST':
        form = TodoForm(data=request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            return redirect('core:todo_list')
        else:
            # FIXME: send error message to todo list page
            return redirect('core:todo_list')


@login_required
def edit_todo_form(request, todo_id):
    """
    Django view.
    Display edit Todo form and handle editing of existing Todo objects.

    :param request: Django request
    :param todo_id: id of the Todo to update
    :return: rendered todo_form template if permissions valid, otherwise redirects to list view
    """
    try:
        todo = Todo.objects.get(id=todo_id)

        # if the todo doesn't belong to that user, raise exception
        if todo.user != request.user:
            raise PermissionDenied

    except (ObjectDoesNotExist, PermissionDenied):
        return redirect('core:todo_list')

    if request.method == 'GET':
        context = {'form': TodoForm(instance=todo), 'form_type': 'edit'}
        return render(request, 'todo_form.html', context)

    if request.method == 'POST':
        form = TodoForm(data=request.POST, instance=todo)
        if form.is_valid():
            form.save()
        # FIXME: send error message to todo list page if form not valid

        return redirect('core:todo_list')


@login_required
def delete_todo(request, todo_id):
    """
    Django view.
    Delete a Todo object.

    :param request: Django request
    :param todo_id: id of the Todo to delete
    :return: redirect to list view
    """

    try:
        todo = Todo.objects.get(id=todo_id)

        # if the todo doesn't belong to that user, raise exception
        if todo.user != request.user:
            raise PermissionDenied

    except (ObjectDoesNotExist, PermissionDenied):
        return redirect('core:todo_list')

    todo.delete()
    return redirect('core:todo_list')

todo/core/templates/about.html
{% extends 'base.html' %}
{% block body %}
<div class="row">
    <div class="col-6 offset-3 my-4">
        <div class="card">
            <h3 class="card-header text-center py-3">
                <i class="bi bi-info-square"></i> About
            </h3>
            <div class="card-body">
                <div class="card-body">
                    <h5 class="card-title">To-do Web Application</h5>
                    This is a mini web application I built in one week as a knowledge assessment.
                    After submitting, I have been adding extra features here and there for fun.<br>
                    This web app is functioning as a stand-in for my portfolio website, which is currently under construction.<br>
                    Feel free to take a look around or check out the
                    <a href="https://github.com/DanielOldham/todo" target="_blank">Github</a>!
                    <h5 class="card-title pt-3">Features</h5>
                    <ul>
                        <li>
                            User accounts
                        </li>
                        <li>
                            User signup / login / logout functionality
                        </li>
                        <li>
                            To-do list page
                        </li>
                        <li>
                            To-do completion
                        </li>
                        <li>
                            Edit To-do functionality
                        </li>
                        <li>
                            Delete To-do functionality
                        </li>
                        <li>
                            List filter functionality (keyword, To-do status)
                        </li>
                        <li>
                            Responsive pagination and filtering with Server Sent Events
                        </li>
                        <li>
                            Unit tested views, forms, and models
                        </li>
                    </ul>
                    <h5 class="card-title">Stack / Tools</h5>
                    <ul>
                        <li>
                            Python Django 5
                        </li>
                        <li>
                            PostgreSQL
                        </li>
                        <li>
                            Bootstrap CSS and Bootstrap Icons
                        </li>
                        <li>
                            Git / Github
                        </li>
                        <li>
                            <a href="https://github.com/carltongibson/django-template-partials" target="_blank">
                                Django Template Partials
                            </a>
                        </li>
                        <li>
                            <a href="https://data-star.dev" target="_blank">Datastar</a>
                        </li>
                        <li>
                            <a href="https://fly.io" target="_blank">Fly.io</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

todo/core/templates/base.html
{% extends 'base_header.html' %}
{% block outer_body %}
<nav class="navbar navbar-expand navbar-dark bd-navbar fixed-top" id="nav-header">
    <div class="container-fluid">
        <div class="navbar-brand ps-3">
            <i class="bi bi-check2-square"></i>
            To-do
        </div>
        <ul class="navbar-nav me-auto">
            {% if request.user.is_authenticated %}
            <li>
                <a class="nav-item nav-link" href="{% url 'core:todo_list' %}">
                    <i class="bi bi-card-checklist"></i>
                    List
                </a>
            </li>
            {% endif %}
            <li>
                <a class="nav-item nav-link" href="{% url 'core:about' %}">
                    <i class="bi bi-info-square"></i>
                    About
                </a>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:logout' %}">
                    Log out
                    <i class="bi bi-box-arrow-right"></i>
                </a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:login' %}">
                    Log in
                    <i class="bi bi-door-open"></i>
                </a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="my-5 container-fluid" id="card-space">
    {% block body %}
    {% endblock %}
</div>

<nav class="navbar navbar-expand navbar-dark fixed-bottom" id="nav-footer">
    <div class="container-fluid">
        <ul class="nav navbar-nav ms-auto navbar-right">
            <li class="nav-item">
                <a class="nav-item nav-link" href="https://github.com/DanielOldham/todo" target="_blank">
                    <i class="bi bi-github"></i>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-item nav-link" href="https://www.linkedin.com/in/daniel-r-oldham" target="_blank">
                    <i class="bi bi-linkedin"></i>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-item nav-link" href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" target="_blank">
                    <i class="bi bi-youtube"></i>
                </a>
            </li>
        </ul>
    </div>
</nav>

{% endblock %}

todo/core/templates/login.html
{% extends 'base.html' %}
{% block body %}
    <div class="row">
        <div class="col-6 offset-3">
            <div class="card my-4">
                <div class="card-header text-center">
                    <h1>
                        <i class="bi bi-door-open"></i>
                        Log in to access your To-dos!
                    </h1>
                </div>

                {# possible errors #}
                {% if form.errors %}
                    <div class="card-body">
                        <ul class="list-group">
                            {% for field, errors in form.errors.items %}
                                {% for error in errors %}
                                    <li class="list-group-item list-group-item-danger">{{error}}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}

                {# login form #}
                <form method="POST">
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="card-body d-grid gap-2 col-10 mx-auto">
                            <h5 class="card-title">{{ field.label }}</h5>
                            <div class="card-text">{{ field }}</div>
                        </div>
                    {% endfor %}

                    <div class="card-body">
                        <div class="d-grid gap-6 col-6 mx-auto">
                            <input type="submit" class="btn btn-block btn-primary" value="Login">
                        </div>
                    </div>
                </form>

                <div class="text-center pb-3">
                    <a href="{% url 'core:signup' %}">Don't have an account? Click here to sign up!</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

todo/core/templates/todo_form.html
{% extends 'base.html' %}
{% block body %}
    <div class="row">
        <div class="col-6 offset-3">
            <div class="card my-4">
                <div class="card-header text-center">
                    <h1>
                        <i class="bi bi-check2-square"></i>
                        {% if form_type == 'add' %}
                        Add New To-do
                        {% else %}
                        Edit To-do
                        {% endif %}
                    </h1>
                </div>

                {# possible errors #}
                {% if form.errors %}
                    <div class="card-body">
                        <ul class="list-group">
                            {% for field, errors in form.errors.items %}
                                {% for error in errors %}
                                    <li class="list-group-item list-group-item-danger">{{error}}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}

                {# todo form #}
                <form method="POST">
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="card-body d-grid gap-2 col-10 mx-auto">
                            <h5 class="card-title">{{ field.label }}</h5>
                            <div class="card-text">{{ field }}</div>
                        </div>
                    {% endfor %}

                    <div class="card-footer mt-4">
                        <div class="row">
                            <div class="col-4 {% if form_type == 'add' %}offset-2{% endif %} text-center">
                                <a class="btn btn-block btn-primary" href="{% url 'core:todo_list' %}">
                                    <i class="bi bi-arrow-return-left"></i>
                                    Cancel
                                </a>
                            </div>
                            <div class="col-4 text-center">
                                <input type="submit" class="btn btn-block btn-primary" value="Submit">
                            </div>
                            {% if form_type == 'edit' %}
                                <div class="col-4 text-center">
                                    <a class="btn btn-block btn-danger" href="{% url 'core:delete_todo' form.instance.id %}">
                                        Delete
                                        <i class="bi bi-trash3"></i>
                                    </a>
                                </div>
                            {% endif %}
                        </div>

                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

todo/core/templates/todo_list.html
{% extends 'base.html' %}
{% load partials %}
{% block body %}
<div class="row">
    {# filter card #}
    <div class="col-3 offset-1 my-4">
        <div class="card">
            <h3 class="card-header text-center py-3">
                Filter
            </h3>

            <div class="card-body">
                <ul data-signals-status
                    class="list-group list-group-flush">
                    <li class="list-group-item">
                        <div class="d-flex justify-content-center">
                            <input data-bind-keyword
                                   data-on-input__debounce.250ms="@get('{% url "core:todo_list" %}')"
                                   type="text" name="keyword" id="keyword" class="form-control" placeholder="keyword">
                            <label for="keyword" hidden>keyword</label>
                        </div>
                    </li>
                    <li class="list-group-item">
                        <div class="d-flex justify-content-center">
                            <input data-on-click="$status='all'; @get('{% url "core:todo_list" %}')"
                                   type="radio" class="btn-check" name="filter-options" value="all" id="all" autocomplete="off" checked>
                            <label class="btn" for="all">All</label>
                        </div>
                    </li>
                    <li class="list-group-item justify-content-center">
                        <div class="d-flex justify-content-center">
                            <input data-on-click="$status='pending'; @get('{% url "core:todo_list" %}')"
                                   type="radio" class="btn-check" name="filter-options" value="pending" id="pending" autocomplete="off">
                            <label class="btn" for="pending">Pending</label>
                        </div>
                    </li>
                    <li class="list-group-item">
                        <div class="d-flex justify-content-center">
                            <input data-on-click="$status='completed'; @get('{% url "core:todo_list" %}')"
                                   type="radio" class="btn-check" name="filter-options" value="completed" id="completed" autocomplete="off">
                            <label class="btn" for="completed">Completed</label>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    {# list card #}
    <div class="col-7 my-4">

        {% partialdef todo_list_card %}
        <div class="card" id="todo_list_card">
            <h3 class="card-header text-center py-3">
                <span style="color: white !important;"></span>{{ request.user.first_name }}<span style="color: white !important;">'s To-do List</span>
            </h3>

            <div class="card-body">
                <ul class="list-group list-group-flush">
                     <li class="list-group-item">
                        <div class="row">
                            <div class="col-1">
                                <a href="{% url 'core:new_todo_form' %}">
                                    <i class="bi bi-plus-square-fill primary-color"></i>
                                </a>
                            </div>
                            <div class="col-11 text-muted">
                                Add new To-do!
                            </div>
                        </div>
                    </li>
                    {% for todo in todos %}
                    <li class="list-group-item">
                        <div class="row {% if todo.status == 'C' %} text-decoration-line-through{% endif %}">
                            {# todo checkbox #}
                            <div class="col-1">
                                <a href="{% url 'core:change_todo_status' todo.id %}">
                                    {% if todo.status == 'C' %}
                                    <i class="bi bi-check-square primary-color"></i>
                                    {% else %}
                                    <i class="bi bi-square primary-color"></i>
                                    {% endif %}
                                </a>
                            </div>

                            {# todo title #}
                            <div class="col-4 fw-bold text-truncate">
                                {{ todo.title }}
                            </div>

                            {# todo notes #}
                            <div class="col-6 text-truncate fst-italic">
                                {{ todo.notes }}
                            </div>

                            {# edit todo button #}
                            <div class="col-1">
                                <a href="{% url 'core:edit_todo_form' todo.id %}">
                                    <i class="bi bi-pencil-square primary-color"></i>
                                </a>
                            </div>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="card-footer">
                <div class="row align-items-center">
                    {# spacer col (may include changeable page amount #}
                    <div class="col">
                    </div>

                    {# pagination control col #}
                    <div data-signals-page class="col">
                        <ul class="pagination justify-content-center mt-2">
                            {# first button and previous button #}
                            {% if todos.has_previous %}
                            <li class="page-item">
                                <button data-on-click="$page='1'; @get('{% url "core:todo_list" %}')" class="page-link" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </button>
                            </li>
                            <li class="page-item">
                                <button data-on-click="$page='{{ todos.previous_page_number }}'; @get('{% url "core:todo_list" %}')" class="page-link">
                                    {{ todos.previous_page_number }}
                                </button>
                            </li>
                            {% else %}
                            <li class="page-item disabled">
                                <button class="page-link">
                                    <span aria-hidden="true">&laquo;</span>
                                </button>
                            </li>
                            {% endif %}

                            {# current button #}
                            <li class="page-item active"><a class="page-link">{{ todos.number }}</a></li>

                            {# next button and last button #}
                            {% if todos.has_next %}
                            <li class="page-item">
                                <button data-on-click="$page='{{ todos.next_page_number }}'; @get('{% url "core:todo_list" %}')" class="page-link">
                                    {{ todos.next_page_number }}
                                </button>
                            </li>
                            <li class="page-item">
                                <button data-on-click="$page='{{ todos.paginator.num_pages }}'; @get('{% url "core:todo_list" %}')" class="page-link">
                                    <span aria-hidden="true">&raquo;</span>
                                </button>
                            </li>
                            {% else %}
                            <li class="page-item">
                                <a class="page-link disabled">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>

                    {# page details column #}
                    <div class="col text-end">
                        <span>
                            Showing
                        </span>
                        <span class="fw-bold">
                            {{ todos.start_index }} - {{ todos.end_index }}
                        </span>
                        <span>
                            of
                        </span>
                        <span class="fw-bold">
                            {{ todos.paginator.count }}
                        </span>
                    </div>
                </div>
            </div>
        </div>
        {% endpartialdef %}
        {% partial todo_list_card %}
    </div>
</div>
{% endblock %}